### ISSUE TITLE
Does the library currently return the References header value?

### ISSUE THREAD

**Issue by lattejed** [emailjs/emailjs-imap-client#101]
I'm wondering if the library currently returns the References header value? Or, are there any plans to support that in the near future?

If not I'll take a look at adding it in. Thanks.

**Comment by asutherland** [comment]
You can retrieve the references header value by doing a fetch like `BODY.PEEK[HEADER.FIELDS (REFERENCES)]`.  Processing and normalizing the contents of the references header would normally be done at a higher level like rfc2822 MIME parsing or higher level threading logic built on top of that.  This is especially true for clients that download the entirety of the MIME message themselves and/or otherwise have to deal with other protocols (POP3, ActiveSync in certain modes), etc.) where raw MIME parsing is required and centralizing the logic in the IMAP protocol library does not make sense.

For example, the Firefox OS multi-protocol mail app uses/used the following logic and abstractions: https://github.com/asutherland/gaia-email-libs-and-more/blob/f876cfb9095e470343139c72858fef1eb87f5e47/js/mime/mime_header_info.js#L9

**Comment by lattejed** [comment]
I'm not 100% sure that I understand what you're saying here. Are you saying that the `References ` header field should not be handled by the library since it's a special case? As I understand it, it's a standard header field (and along with `Message-ID` and `In-Reply-To` is usually used for organizing threads) so shouldn't the library fetch and parse it if requested?

Again, I don't mind adding this into the library myself but I want to make sure we're on the same page about it. I believe it's a standard header field and since the library fetches / parses other header fields should also do this one?

Thanks.

**Comment by asutherland** [comment]
Sorry for the lack of clarity in my response; although I've contributed to these libs, it's always been Andris and Tankred with the vision, etc :)

Does emailjs-imap-client do a lot of other specialized header parsing?  My understanding was that other than then ENVELOPE parsing at https://github.com/emailjs/emailjs-imap-client/blob/b4ee0b694efb85ea70805b668c3cb400b16e585d/src/emailjs-imap-client.js#L1224 that was left to emailjs-mime-parser, which does have specialized header parsing at https://github.com/emailjs/emailjs-mime-parser/blob/350dc5b4b8804a1c8cba1105713bdd4e54862d07/src/emailjs-mime-parser.js#L524.

As implied by the link, in this family of mail libraries emailjs-mime-parser already does header parsing, so I would use it for that purpose and enhance it to also understand and normalize the threading headers (references, in-reply-to, message-id).  That way the logic only has to exist in one place, etc.  That logic also nicely leaves the original value available as `initial` which is a nice idiom.

For Firefox OS mail, on the dev branch we now use the https://github.com/mozilla-comm/jsmime/ MIME parser that Thunderbird is adapting to, which I think may be an argument in favor of the module structure and separate MIME parsers.  Some translation is needed, with our adaption code living at https://github.com/asutherland/gaia-email-libs-and-more/blob/f876cfb9095e470343139c72858fef1eb87f5e47/js/imap/imapchew.js#L109.

So I think my advice would be:

- Use/enhance the header parsing in emailjs-mime-parser
- If it's awkward to get the headers from emailjs-imap-client into emailjs-mime-parser, then maybe streamline that path in a way that makes sense to you as a consumer and propose that.  I think it would be nice to allow different MIME parsers to still be used, but certainly being able to pass an emailjs-mime-parser constructor/instance into the emailjs-imap-client constructor/factory seems reasonable.  I think Firefox OS mail may have always needed to do some slightly odd translation like in the above case, so I suspect this really can be improved.
- Maybe check out whatever the whiteout.io UI client did?  I don't know where it went source-code-wise, but it probably had to deal with this exact scenario.

**Comment by andris9** [comment]
References are not part of the ENVELOPE value (unlike Message-Id or In-Reply-To). You can fetch it separately as any other header value using the HEADER.FIELDS value. Contextually References is not important as this is an IMAP module and not mime parsing module
