### ISSUE TITLE
Log level options are ignored / reduce verbosity

### ISSUE THREAD

**Issue by jkirkpatrick** [emailjs/emailjs-imap-client#103]
Similar to #14 

The value for the verbosity is hard-coded and can not be adjusted in the options:
https://github.com/emailjs/emailjs-imap-client/blob/d76d3318de2628e95815db3306ed72e978e3c820/src/emailjs-imap-client.js#L67-L69

**Comment by felixhammerl** [comment]
You can change the log level at any time you see fit: 

```javascript
instance.logLevel = this.LOG_LEVEL_DEBUG
```

here's the log levels available: https://github.com/emailjs/emailjs-imap-client/blob/d76d3318de2628e95815db3306ed72e978e3c820/src/emailjs-imap-client.js#L1791-L1796
```
LOG_LEVEL_NONE
LOG_LEVEL_ERROR
LOG_LEVEL_WARN
LOG_LEVEL_INFO
LOG_LEVEL_DEBUG
LOG_LEVEL_ALL
```

Or supply your own logger that conforms to this API in the options used to initialize the imap client: https://github.com/emailjs/emailjs-imap-client/blob/d76d3318de2628e95815db3306ed72e978e3c820/src/emailjs-imap-client.js#L1830

Please inform me if that didn't work and we can re-open this bug.
