### ISSUE TITLE
Unable to verify first Certificate

### ISSUE THREAD

**Issue by simonhochrein** [emailjs/emailjs-imap-client#106]
```
[DEBUG][2016-09-30T20:29:04.465Z][undefined] Entering state: 1
[ERROR][2016-09-30T20:29:04.725Z][undefined] Could not connect to server Error: Could not open socket: unable to verify the first certificate
[DEBUG][2016-09-30T20:29:04.725Z][undefined] Entering state: 5
[DEBUG][2016-09-30T20:29:04.725Z][undefined] Closing connection...
```

Any Ideas?

**Comment by WhatFreshHellIsThis** [comment]
Same here on NODE.JS connecting to our own remote mail server, porting code from C# to javascript, C# code and IMAP settings work fine with server but not in Javascript with this library.

Some kind of cert issue but not sure what it could be, the client doesn't need a cert or knowledge of the cert normally and the mail server works fine with C# code a variety of mail clients on a variety of platforms so it's something I'm doing or in this library, any help appreciated.

Here is my test code:
  ```
var HOST = "mail.REDACTED.com";
    var PORT = 993;
    var OPTIONS = {
        useSecureTransport: true,
        auth: {
            user: 'support@REDACTED.com',
            pass: 'REDACTED'
        },
        id: { name: 'REDACTED', version: '1.x' }
    };

    var client = new ImapClient(HOST, PORT, OPTIONS);

    client.onerror = function (error) {
        return {
            error: 1,
            msg: 'Error @ key-requests->fetchRequests->onError (some kind of IMAP related error, see error_detail)',
            error_detail: error
        }

    }

    client.connect().then(() => {
        /* ready to roll */
        client.listMailboxes().then((mailboxes) => {
            //do something with mailboxes
            client.logout().then(() => {
                /* connection terminated */
                client.close().then(() => {
                    /* connection terminated */
                    callback({
                        test: 1,
                        ok: 1,
                        STUB_RESULT: 1
                    })
                });
            });
        })
    });

```

[DEBUG][2017-03-09T23:37:07.920Z][1] Connecting to mail.REDACTED.com : 993
[DEBUG][2017-03-09T23:37:07.924Z][1] Entering state: 1
[ERROR][2017-03-09T23:37:12.510Z][1] Could not connect to server Error: Could not open socket: unable to verify the first certificate
[DEBUG][2017-03-09T23:37:12.510Z][1] Entering state: 5
[DEBUG][2017-03-09T23:37:12.510Z][1] Closing connection...

**Comment by WhatFreshHellIsThis** [comment]
Dug into the code, this is not actually related to this repository, it's coming from the node socket library.

Looks like there is some confusion with the cert we are using, it's accepted by other code, just not by the node socket.  

Since this is an internal facing only application I've worked around it by doing this:
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
Which temporarily overrides and allows it to work with our faulty cert.  

This is entirely unsafe to do in most other circumstances, more info here: http://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs

**Comment by simonhochrein** [comment]
Forgot about this thread, closing

**Comment by aligatorr89** [comment]
> Dug into the code, this is not actually related to this repository, it's coming from the node socket library.
> 
> Looks like there is some confusion with the cert we are using, it's accepted by other code and libraries on other platforms and clients, just not by the node socket.
> 
> Since this is an internal facing only application I've worked around it by doing this:
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
> Which temporarily overrides and allows it to work with our faulty cert.
> 
> This is entirely unsafe to do in most other circumstances, more info here: http://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs

Great solution man, it works!!!

**Comment by felixhammerl** [comment]
> I've worked around it by doing this:
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

**DO NOT DO THIS**!
If you have a custom domain, please use proper certificates via letsencrypt. If this is for testing, please generate a trusted certificate via [mkcert](https://github.com/FiloSottile/mkcert)!

**Comment by aligatorr89** [comment]
> > I've worked around it by doing this:
> > process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
> 
> **DO NOT DO THIS**!
> If you have a custom domain, please use proper certificates via letsencrypt. If this is for testing, please generate a trusted certificate via [mkcert](https://github.com/FiloSottile/mkcert)!

Thanks, ill check it out. Like others, im having problems with IMAP connect. This problems started today out of nowhere, it worked for more than 2 weeks.
