### ISSUE TITLE
README.md : The listMessages() example is missing an argument

### ISSUE THREAD

**Issue by ybouhjira** [emailjs/emailjs-imap-client#109]
```
client.listMessages('1:10', ['uid', 'flags', 'body[]']).then((messages) => {
    messages.forEach((message) => console.log('Flags for ' + message.uid + ': ' + message.flags.join(', ')));
});
```

I think this example is missing the `PATH` argument which comes first, as described in the README file
- **path** is the path for the mailbox which should be selected for the command. Selects mailbox prior to executing FETCH if not already selected.
  - **sequence** defines the range of sequence numbers or UID values (if `byUid` option is set to true). Example: '1', '1:*', '1,2:3,4' etc.
  - **query** is an array of keys that need to be fetched. Example: ['uid', 'flags', 'body.peek[headers (date)]']
  - **options** is an optional options object
    - **byUid** if `true` executes `UID FETCH` instead of `FETCH`
    - **changedSince** is the modseq filter. Only messages with higher modseq value will be returned

**Comment by Axel186** [comment]
That's what I thought before - just like you.
I'm not sure - but, I think if you selecting mailbox with function **selectMailbox()** - script knows that you already uses this mailbox, so there is no need to use **path** parameter.

I'm using **path** parameter anyway =D, but need to check if it works without.

**Comment by dwaps** [comment]
I have an exception if I don't put the path argument (even if I pass through selectMailbox() )...
I just sent a mail to the authors for ask to change that (to spare the future victims spending time to looking)
