### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by hamzazer** [emailjs/emailjs-imap-client#110]
Hi,

I think i found a problem in the authentication problem, it occur when the password contains the character "\\":

```javascript
auth: {
    user: 'test@example.com',
    pass: 'password\password'
}
```
###### Solution (escape the "\\" char)
```javascript
auth: {
    user: 'test@example.com',
    pass: 'password\\password'
}
```

**Comment by asutherland** [comment]
This is expected Javascript language behavior.  The backslash character ("\") has special significance.  If you want an actual backslash character in your string, you need to escape it.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Escape_notation for more information on that.
