### ISSUE TITLE
SSL against Exchange IMAP not working

### ISSUE THREAD

**Issue by matthiasg** [emailjs/emailjs-imap-client#111]
Using emailjs-imap-client i cannot establish a TLS connection to an exchange IMAP server via TLS. 

I get:
```
[DEBUG][2016-12-08T07:44:26.738Z][1] Connecting to 192.168.1.101 : 993
[DEBUG][2016-12-08T07:44:26.747Z][1] Entering state: 1
[ERROR][2016-12-08T07:44:26.843Z][1] Could not connect to server Error: Could not open socket: 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

[DEBUG][2016-12-08T07:44:26.843Z][1] Entering state: 5
[DEBUG][2016-12-08T07:44:26.847Z][1] Closing connection...
(node:31136) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not open socket: 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
```

connecting without tls to the default 143 port works. Connecting to the secure port with other imap libraries such as 'imap-client' also works. Is there anything not implemented in emailjs-imap-client with respect to secure imap or am i doing something wrong ?

**Comment by felixhammerl** [comment]
What platform are you on?

**Comment by matthiasg** [comment]
windows 10 64bit. with node v6.9.1

**Comment by matthiasg** [comment]
connecting against another non exchange IMAP server with ssl works fine  btw.

**Comment by matthiasg** [comment]
thinking this through this might be caused by the exchange server not having an officially trusted certificate. my machine does trust the server but node wouldn't know how to access that. i will have a look at the ca option.
