### ISSUE TITLE
Disable logger

### ISSUE THREAD

**Issue by simonmilz** [emailjs/emailjs-imap-client#112]
Correct me if i'm wrong, but there is no way to disable the logger? I don't wan't to log every action on my production environment ;)

**Comment by felixhammerl** [comment]
you can set the logger to LOG_LEVEL_NONE
https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client.js#L1829

**Comment by felixhammerl** [comment]
or you could create a no-op logger. a PR would be welcome :)

**Comment by simonmilz** [comment]
Due to the fact that the log level is set hardcoded to `LOG_LEVEL_ALL` in https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client.js#L69 i will create a PR for that. Give me some days ;)

**Comment by felixhammerl** [comment]
but why not just do `imap.logLevel = LOG_LEVEL_NONE` ?

**Comment by simonmilz** [comment]
Thanks! That works as expected.
