### ISSUE TITLE
How many simultaneous IMAP email accounts can this client handle?

### ISSUE THREAD

**Issue by neatcode** [emailjs/emailjs-imap-client#113]
On a single, say $2500 dedicated server (average high end server), how many simultaneous connected  IMAP email accounts do you think this client could handle?

Ie. how scalable is this client? assuming everything else is dummy code but the dummy code performs actions on each user account every 10 minutes or so like LIST or FETCH. assume db interaction is "free" in terms of performance for the purposes of this question.

just looking for a ball-park.

**Comment by andris9** [comment]
I guess it mostly depends on the available RAM and CPU. You can create a lot of imap-client instances but you would most probably need to shard these between different processes (maybe 1000 connections per process?). This client is not optimized for server use so you might have problems if you have a lot of large messages coming in simultaneously (you can use IMAP range queries though to mitigate this).
