### ISSUE TITLE
rejectUnauthorized equivalent?

### ISSUE THREAD

**Issue by casalot** [emailjs/emailjs-imap-client#114]
Is there an equivalent for `rejectUnauthorized` in the `options` object?

Platform:
- Ubuntu 14.0.4
- NodeJS 6.2

**Comment by casalot** [comment]
Okay, I resolved this by setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"` in my module, as `ignoreTLS` and `requireTLS` had no real effect.

This works well now.

**Comment by felixhammerl** [comment]
Be aware that this open the connections to MitM attacks of any sort, effectively making TLS useless ...
