### ISSUE TITLE
Getting email content by message.id

### ISSUE THREAD

**Issue by LectorRSS** [emailjs/emailjs-imap-client#115]
How i can get the mail content by message.uid?
I testing emaijs-imap with electron, i got this

client.connect().then(() => {

		var mailbox = client.selectMailbox('INBOX');

		client.listMessages('INBOX', '1:10', ['uid', 'flags', 'envelope', 'bodystructure', 'body.peek[headers (date)]']).then((messages) => {
            messages.forEach((message) => { 

                console.log("Body:" + message.body );

            	console.log('Flags for ' + message.uid + ' | De:  ' + message.envelope.from[0].name + ' (' + message.envelope.from[0].address + ') Asunto:' + message.envelope.subject);
            

		//client.logout();

});

How i can get mail content.. html or text.

Thanks!

**Comment by andris9** [comment]
For the full rfc822 message use `body.peek[]`. This module is for handling IMAP only, you have to parse the resulting raw message yourself

**Comment by LectorRSS** [comment]
How? some repo? info? link? how to?

Please

**Comment by andris9** [comment]
You should be able to handle everything using this and other emailjs modules: http://emailjs.org/

Once you have a rfc822 formatted email you can parse it with the emailjs mime parser. For a complete application that handles all required parts using these modules, see [hoodiecrow](https://github.com/tanx/hoodiecrow)

**Comment by andris9** [comment]
Oh, sorry, I meant [Whiteout client](https://github.com/whiteout-io/mail) as the example, Hoodiecrow is using gmail API only
