### ISSUE TITLE
Unexpected Untagged Response Error

### ISSUE THREAD

**Issue by marcus433** [emailjs/emailjs-imap-client#117]
I ran a `FETCH` command and received a `HIGHESTMODSEQ` unexpected untagged response before the `FETCH` resulted were received. Likely the untagged response was due to the `UID FETCH` also asking for the `MODSEQ`.

The issue is the untagged response triggered this part of the response handler
https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client-imap.js#L475
which sets _canSend to true and runs a _sendRequest. I had a `STATUS` command I sent following the `FETCH` and due to the untagged response setting _canSend to true the `STATUS` command was set as the _currentCommand. This meant that when the `FETCH` success response was received it never resolved the promise as the _currentCommand tag didn't match.

I found the solution to this to be removing 
```
            this._canSend = true;
            this._sendRequest();
```
from the unexpected untagged response handler. I'm not sure whether this is proper, but to me it makes sense as a unexpected untagged response is not a response to the _currentCommand and thus shouldn't allow _canSend as _currentCommand may not have finished.

If this is indeed correct I am more than happy to submit a pull request.

**Comment by marcus433** [comment]
This issue is fixed in pull request: https://github.com/emailjs/emailjs-imap-client/pull/128

**Comment by nifgraup** [comment]
#128 is now on master
