### ISSUE TITLE
Cannot get onupdate to work reliably

### ISSUE THREAD

**Issue by matthiasg** [emailjs/emailjs-imap-client#118]
I was under the assumption that on `client.onupdate` would be called when e.g a mail is changed on the server. this does work with the gmail server but quite time delayed and it does not work e.g with a standard mail server from hetzner. `onupdate` is basically never called for e.g flag changes or very intermittently at least.

From the documentation I assume I have to first call `client.selectMailbox` with `condstore:true` to even hope to get it working correctly. If it doesnt work with the non Gmail servers I test against, does that mean that the servers dont behave correctly ? Does anybody know how widely supported this quicksync (https://tools.ietf.org/html/rfc7162) feature is ?

Is anybody using this ?

**Comment by andris9** [comment]
Flag changes are not part of CONDSTORE. What you want is untagged FETCH notifications that are catched by `onupdate`. CONSTORE (if enabled) gives you modsequence numbers along with the new flags but this is not required (even though it helps a lot). If the server does not send untagged updates for flag changes then you can also never receive these. Whats the software used by Hetzner?

**Comment by matthiasg** [comment]
@andris9 I did not find that out yet. I opened a ticket with them. What I am looking for is a way to rather quickly sync a flag change made on one device to another server also watching that same IMAP mailbox.

**Comment by matthiasg** [comment]
btw connection protocol to hetzner is

```
[DEBUG][2017-01-04T13:39:53.298Z][1] Connecting to mail.your-server.de : 993
[DEBUG][2017-01-04T13:39:53.310Z][1] Entering state: 1
[DEBUG][2017-01-04T13:39:53.436Z][1] Socket opened, waiting for greeting from the server...
[DEBUG][2017-01-04T13:39:53.512Z][1] S: * OK [CAPABILITY IMAP4 IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy03.your-server.de 0002eb6b
[DEBUG][2017-01-04T13:39:53.515Z][1] Entering state: 2
[DEBUG][2017-01-04T13:39:53.517Z][1] Logging in...
[DEBUG][2017-01-04T13:39:53.518Z][1] C: W1 login "***@***" "(* value hidden *)"
[DEBUG][2017-01-04T13:39:53.642Z][1] S: W1 OK You are so in
[DEBUG][2017-01-04T13:39:53.643Z][1] Updating capability...
[DEBUG][2017-01-04T13:39:53.645Z][1] C: W2 CAPABILITY
[DEBUG][2017-01-04T13:39:53.668Z][1] S: * CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION
[DEBUG][2017-01-04T13:39:53.668Z][1] S: W2 OK CAPABILITY completed
[DEBUG][2017-01-04T13:39:53.670Z][1] Entering state: 3
[DEBUG][2017-01-04T13:39:53.671Z][1] Login successful, post-auth capabilites updated! IMAP4REV1,UIDPLUS,CHILDREN,NAMESPACE,THREAD=ORDEREDSUBJECT,THREAD=REFERENCES,SORT,QUOTA,IDLE,AUTH=PLAIN,ACL,ACL2=UNION
[DEBUG][2017-01-04T13:39:53.672Z][1] Connection established, ready to roll!
```

**Comment by matthiasg** [comment]
in general even with GMail the fetch updates are called quite infrequently it seems even if i set a flag directly on the gmail website it is not predictable how long it takes for the 'fetch' update to come in

**Comment by matthiasg** [comment]
I tried that just now . Waited for it to idle. Then changed flags directly i. At first I did not get any changes and waited a minute nothing happened. Then I used a Mail Client to also change some flags and I did get an update. But only two. Trying again by removing or adding flags afterwards did not push update in a timely or predictable manner. So I guess I will have to implement polling here

```
DEBUG][2017-01-04T13:44:06.769Z][1] Client started idling
[DEBUG][2017-01-04T13:44:06.770Z][1] Entering idle with IDLE
[DEBUG][2017-01-04T13:44:06.772Z][1] C: W7 IDLE
[DEBUG][2017-01-04T13:45:06.774Z][1] Idle terminated
[DEBUG][2017-01-04T13:45:06.796Z][1] S: W7 OK IDLE completed
[DEBUG][2017-01-04T13:45:07.796Z][1] Client started idling
[DEBUG][2017-01-04T13:45:07.796Z][1] Entering idle with IDLE
[DEBUG][2017-01-04T13:45:07.797Z][1] C: W8 IDLE
[DEBUG][2017-01-04T13:46:07.798Z][1] Idle terminated
[DEBUG][2017-01-04T13:46:07.820Z][1] S: * 3 FETCH (FLAGS (\Flagged \Seen))
onupdate INBOX fetch { '#': 3, flags: [ '\\Flagged', '\\Seen' ] }
[DEBUG][2017-01-04T13:46:07.822Z][1] S: * 4 FETCH (FLAGS (\Seen))
onupdate INBOX fetch { '#': 4, flags: [ '\\Seen' ] }
[DEBUG][2017-01-04T13:46:07.823Z][1] S: W8 OK IDLE completed
[DEBUG][2017-01-04T13:46:08.824Z][1] Client started idling
[DEBUG][2017-01-04T13:46:08.824Z][1] Entering idle with IDLE
[DEBUG][2017-01-04T13:46:08.824Z][1] C: W9 IDLE
```

**Comment by andris9** [comment]
Yeah, propagating flag changes in a large email system is really complicated, it took Gmail literally years to start sending these notifications at all. If condstore is enabled then you can use the `changedSince` modifier - you need to keep count of the last seen `mailbox.highestModseq` or `message.modseq` and provide this value to `listMessages`

```javascript
client.listMessages('INBOX', '1:*', ['uid', 'flags', 'modseq'], {
    changedSince: lastKnownHighestModseq
}).then((messages) => {
    messages.forEach((message) => console.log('Flags for ' + message.uid + ': ' + message.flags.join(', ')));
});
```

**Comment by matthiasg** [comment]
Thanks.

Since I can detect the capability I can notify users of the potential delay or polling mechanics. At least it works with gmail. Will be interesting to see whether microsoft exchange supports that, but  I cannot test against our servers because SSL wont work until I get custom certs to be accepted.
