### ISSUE TITLE
Retrieve Server announced CAPABILITY 

### ISSUE THREAD

**Issue by matthiasg** [emailjs/emailjs-imap-client#119]
When connecting to an IMAP server (sometime before or after login) the server usually returns a CAPABILITY

e.g.
```
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- APPENDLIMIT=35651584
```

for gmail right now or 

```
* OK [CAPABILITY IMAP4 IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy03.your-server.de 0002eb6b
```

for a Hetzner server of ours.

Is there any way this information could be exposed ? Or is it already and I did not see it ?

We would like to check for CONDSTORE capability to warn users if this feature is missing.

**Comment by andris9** [comment]
Capability options are detected from such constructs and you should be able to access the capability listing from the `client._capability` array. So you should be able to do something like this:

```javascript
if(client._capability && client._capability.includes('CONDSTORE')){
    alert('CONDSTORE is supported!');
}
```

**Comment by matthiasg** [comment]
@andris9 thanks. I had assumed _capability  was an internal property and I try not to use those by default :)

**Comment by andris9** [comment]
Yeah, it is internal. But I don't see how it could change any time soon as there is not much happening with the emailjs project currently, it is pretty much frozen.

**Comment by andris9** [comment]
CONDSTORE is enabled with the SELECT/EXAMINE command like this:

```
C: A142 SELECT INBOX (CONDSTORE)
```

See [rfc4551#section-3.7](https://tools.ietf.org/html/rfc4551#section-3.7) for details.

**Comment by matthiasg** [comment]
I had read rfc5161 to supersede rfc4551 as in you first have to enable it to then use it. but since gmail works I must have misunderstood. Thanks!

**Comment by andris9** [comment]
ENABLE and CONSTORE are different extensions. `ENABLE` makes any change permanent, having `(CONDSTORE)` argument for `SELECT` enables CONDSTORE for that mailbox session only. In retrospect there's not much difference, these extensions usually go in pair so emailjs could have used just as well the ENABLE command.
