### ISSUE TITLE
Support for the APPEND command

### ISSUE THREAD

**Issue by nkman** [emailjs/emailjs-imap-client#122]
One of our client program needs to use the `APPEND` command described [here](https://tools.ietf.org/html/rfc3501#section-6.3.11)

I could not find this command here in this client, are we going to have this command anytime soon here?

**Comment by andris9** [comment]
Try to use the uncodumented [upload](https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client.js#L509) method
