### ISSUE TITLE
TCPSocket timeout dead end

### ISSUE THREAD

**Issue by shiraishimai** [emailjs/emailjs-imap-client#123]
Promise is resolved by onready() before IMAP.client invoking onerror() on TCPSocket timeout,
thus the Promise cannot be re-reject in the promise chain.

**Comment by felixhammerl** [comment]
the socket being ready means that the connection is up. if that happens, everything should be fine. can you shed some more light on what happens in your case?

**Comment by shiraishimai** [comment]
Hi @felixhammerl ,
the timeout error is defined inside 
https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client-imap.js#L301
I guess it has never been tested.

In my actual case in production,
the TCPSocket is ready, yes, it is connected, but the Server is not responding after the TCP connection, causing the timeout forementioned,
as Promise on
https://github.com/emailjs/emailjs-imap-client/blob/master/src/emailjs-imap-client.js#L97
has already been resolved by `this.client.onready()`
the error is not rejected properly on `this.client.onerror()` and is gone silently.

**Comment by nifgraup** [comment]
@shiraishimai is this still a problem on master now with  #133 merged?
