### ISSUE TITLE
Question: Detect auto-logout

### ISSUE THREAD

**Issue by Munawwar** [emailjs/emailjs-imap-client#142]
Hi.
I have a long-running imap session. After few hours I see gmail auto-logging out (I think) and no new mails are processed on onupdate() event.
I see the following debug log:
`[imap.gmail.com] S: * BYE Session expired, please login again.`

Is there a way to detect this scenario and re-connect?

Thanks

**Comment by andris9** [comment]
Just to clarify, how to you authenticate against Gmail, do you use plain passwords or OAuth2?

**Comment by Munawwar** [comment]
I initially thought the connection isn't being closed as I couldn't find any logs on it. But I found it out; imap.onerror event is indeed being called at that point in time, as socket is closed by Gmail.

Hmm...however the message I get is a generic "Socket closed unexpectedly" message, and probably cannot be used to determine that Gmail intentionally did that. So I can add some connection retries (3 times) and quit after that. I think good enough for now.

Thanks
