### ISSUE TITLE
Haraka vs emailjs vs WildDuck

### ISSUE THREAD

**Issue by Extarys** [emailjs/emailjs-imap-client#150]
It's getting confusing. I didn't know there was so many options.

I was going to implement standard Dovecot/Postfix etc server. But they are hard to scale compared to what we can achieve with nodejs.

I see there is a lot of updates for the emailjs libraries in general. Should I/Can I implement this as a flow blown mail server?

Thanks guys!

**Comment by felixhammerl** [comment]
Somehow I missed this issue. emailjs are client libs as in they don't provide email MTA or other server functionality. They do however connect to your server of choice. Feel free to use them in your setting :)
