### ISSUE TITLE
Remove Imap folder

### ISSUE THREAD

**Issue by fkrauthan** [emailjs/emailjs-imap-client#157]
How can I remove an Imap folder? I found a method to remove all my emails within a folder but I would also like to remove the folder itself. Is there any way todo that?

**Comment by felixhammerl** [comment]
This has not been implemented yet ...

**Comment by felixhammerl** [comment]
We should look into supporting the DELETE command in order to rename mailboxes. CREATE is already implemented, however the others are missing.

RFC: https://tools.ietf.org/html/rfc3501#section-6.3.4

**Comment by bruno-sartori** [comment]
any update on this?
