### ISSUE TITLE
ANNOUNCEMENT: EmailJS 2017+

### ISSUE THREAD

**Issue by felixhammerl** [emailjs/emailjs-imap-client#158]
Hi y'all,

how do you use the email js libs? I've been on a longer hiatus, but I'm planning on dropping in again more in the future. For that reason, I'd like to re-assess the scope of this project, since some of the basic assumptions changed:

* Chrome Apps is dead, so the dreaded Chrome socket shim can be removed
* Transpilers are up to the task and most really shitty old platforms are gone for good
* An ES2017 refactor will dramatically reduce code
* UMD is gone in favor of webpack and the likes.
* Let's throw out the task runners in favor of shell scripts
* Standardjs linting

What do y'all think about this?
On which platforms are you using emailjs?

EDIT:
This happens in a major version bump, so y'all can continue pretty much undisturbed.

**Comment by nifgraup** [comment]
Sounds good. Getting 2 spaces in return for losing the semi colon seems like a fair trade, but I'm not going to bikeshed JS lint style :). We use emailjs at Vivaldi with the chrome.socket API. It is still working in the Chromium project but eventually it will go away. That means either adopting chrome.socket or switching to something else.

**Comment by felixhammerl** [comment]
4 or 2 spaces, I don't care either. But it's a package deal and standardjs is a pretty good linter with a decent code style that works out of the box, so i'll take the 2 spaces :)

I'll see to it that compatibility need not be unnecessarily broken. It the socket shim causes problems, I'll think about removing it. Downside is the cost of having to rewrite the socket code. Let's cross that bridge when we get there :)

**Comment by felixhammerl** [comment]
@nifgraup found a way to make the tcp socket work after all :)
https://github.com/emailjs/emailjs-tcp-socket
