### ISSUE TITLE
emailJS babel polyfill Ionic2 

### ISSUE THREAD

**Issue by osterland** [emailjs/emailjs-imap-client#165]
Hi Guys, 

im developing an Ionic2 app and would love to integrate emailJS. Since Ionic2 uses es2015 we run in some generatorRuntime errors and tried to get rid of them with the babel-polyfill.js and so on. But we are not gettin it to work. Any hints or any workin emailJs + Angular or Phonegap integrations, i could get some inspiration from ? 

regards Kevin

**Comment by austein** [comment]
Also having trouble with regeneratorRuntime on Node v8.9.3

**Comment by nrutman** [comment]
Also having this problem in Node v9.3.0. Is there any way to fix this?

**Comment by SidneyNemzer** [comment]
Also had this problem (more details in #166)

**Comment by felixhammerl** [comment]
Closing this issue in favor of https://github.com/emailjs/emailjs-imap-client/issues/166

**Comment by felixhammerl** [comment]
resolved #166, plz check again.
