### ISSUE TITLE
Error: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by SidneyNemzer** [emailjs/emailjs-imap-client#166]
## Code

```javascript
import ImapClient from 'emailjs-imap-client'

const options = {
  auth: {
    user: '<removed>',
    pass: '<removed>'
  }
}

const client = new ImapClient('imap.gmail.com', 993, options)

client.onerror = error => {
  console.log('Email client error:', error)
}

console.log('Connecting...')
client.connect().then(() => {
  console.log('Client connected!')
  console.log('Closing connection...')
  client.close().then(() => console.log('Connection closed'))
})
```

## Expected result

Fairly straight forward. a few logs: client open, client closed. Just to test my connection to gmail.

## Actual result

An error is thrown from the constructor, not from the `client.onerror` handler.

```
$ node .
E:\Documents\GitHub\Repositories\temp\node_modules\emailjs-imap-client\dist\imap.js:500
    value: /*#__PURE__*/regeneratorRuntime.mark(function _iterateIncomingBuffer() {
                        ^

ReferenceError: regeneratorRuntime is not defined
    at E:\Documents\GitHub\Repositories\temp\node_modules\emailjs-imap-client\dist\imap.js:500:25
    at Object.<anonymous> (E:\Documents\GitHub\Repositories\temp\node_modules\emailjs-imap-client\dist\imap.js:1065:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Documents\GitHub\Repositories\temp\node_modules\emailjs-imap-client\dist\client.js:24:13)
```

Indeed, in the file that the error points to:

https://github.com/emailjs/emailjs-imap-client/blob/5616706172514c9337854020af57f23aba479037/dist/imap.js#L500

The variable `regeneratorRuntime` isn't defined anywhere that I can see, at least in that file.

I tried:

1. Running in node (where `import` was swapped with `require`)
2. Running in a browser (after building with parceljs).

So, what am I doing wrong here? I don't see any other issues that mention this error so I must be doing something really silly...

**Comment by osterland** [comment]
looks like reference #165

**Comment by felixhammerl** [comment]
hi y'all, let me dive into the babel configuration later this weekend. didn't have time to respond this week, sorry.

**Comment by felixhammerl** [comment]
Sorry for that, apparently I need to learn how to `babel` correctly. [Updated the babelrc to account for that](https://github.com/emailjs/emailjs-imap-client/blob/master/.babelrc#L4-L7)

Should be fixed in v3.0.2, please retry.

**Comment by SidneyNemzer** [comment]
After building with Parcel and running in a browser, I'm getting `exports is not defined` here:

**Comment by felixhammerl** [comment]
The self-signed warning is b/c you didn't bother to get a proper TLS cert :)
Interesting though that the warning doesn't go through the error handler. Need to look into that.
Check [the tcp-socket repo](https://github.com/emailjs/emailjs-tcp-socket/blob/master/scripts/create-root-CA.sh) to generate a proper self-signed cert. For testing purposes, add that cert to your certificate store. Never skip TLS verification in your production code. If you actually run that somewhere, please set up [Let's Encrypt](https://letsencrypt.org/).

**Comment by felixhammerl** [comment]
Oh, and regarding the Parcel issue: I expose the commonjs representation, not a UMD build. That also assumes a node environment while pulling the modules together. you might need to instruct your bundler to consume commonjs. In the browser, `exports` is not defined. In node, it is a special object exposed to commonjs modules upon parse time (see [the documentation](https://nodejs.org/api/modules.html#modules_exports))
