### ISSUE TITLE
this.ON_DATA_TIMEOUT is undefined

### ISSUE THREAD

**Issue by MarcoCanalcar** [emailjs/emailjs-imap-client#170]
https://github.com/emailjs/emailjs-imap-client/blob/master/src/imap.js#L402
On this line, the value of this.ON_DATA_TIMEOUT is undefined, which, will cause the setTimeout to resolve as soon as posible, and, in some ocasions, end the connection with a 'Socket timed out'

**Comment by TomasHubelbauer** [comment]
I am having the same issue.

**Comment by felixhammerl** [comment]
yep, it seems this was in there before the refactoring and I've missed to fix this line for some weird reason.
