### ISSUE TITLE
Not compatible with NodeJS!?

### ISSUE THREAD

**Issue by jhoermann** [emailjs/emailjs-imap-client#182]
I get this error on startup:
`import ImapClient from 'emailjs-imap-client';
    ^^^^^^

    SyntaxError: Unexpected token import
        at new Script (vm.js:51:7)
        at createScript (vm.js:136:10)
        at Object.runInThisContext (vm.js:197:10)
        at Module._compile (module.js:613:28)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Module.require (module.js:593:17)
        at require (internal/module.js:11:18)
        ...
`

With Node Version:
`node -v
v9.10.1`

As stated here: [https://nodejs.org/api/esm.html#esm_unsupported](https://nodejs.org/api/esm.html#esm_unsupported) NodeJS is not (yet) compatible with 'import'.
My questions:
1. What is the last compatible Version of this module?
2. Why is the version 3.0.7 on npm when its not compatible with node?

Greetings, Jochen

**Comment by felixhammerl** [comment]
You can't just run ES6 code without transpiling it. The lib is transpiled to ES5, your app, however, seems not to be.

**Comment by jhoermann** [comment]
Thanks for clearing this up. Testing now if this is a viable option for our app. Still I think it would be better to notice that this module is not usable natively with node (without using babel) in the Readme.

**Comment by geek4teck** [comment]
> Thanks for clearing this up. Testing now if this is a viable option for our app. Still I think it would be better to notice that this module is not usable natively with node (without using babel) in the Readme.
> 
> Edit: This works for me as a workaround:
> `var ImapClient = require('emailjs-imap-client');`
> `var client = new ImapClient.default(settings.host, settings.port, { ...`

Works for me too :-)
