### ISSUE TITLE
Error: Socket closed unexceptedly!

### ISSUE THREAD

**Issue by jhoermann** [emailjs/emailjs-imap-client#194]
![image](https://user-images.githubusercontent.com/13086717/45613925-18c92280-ba68-11e8-8f1e-9d7b3e983d47.png)

Any ideas how to prevent this error? Are we doing something wrong? Or is this error negligible?

Greetings and thanks for this great module!
Jochen

**Comment by felixhammerl** [comment]
When is that error being thrown? When you start the socket or when it's idling for a while?

**Comment by jhoermann** [comment]
When its idling for a while. This just happens sometimes.

**Comment by SunriseFox** [comment]
> When is that error being thrown? When you start the socket or when it's idling for a while?

I believe it is a bug. See #195

**Comment by jhoermann** [comment]
> > When is that error being thrown? When you start the socket or when it's idling for a while?
> 
> I believe it is a bug. See #195

Great, thanks for your work. Hopefully it'll get pulled soon.

**Comment by eakriulin** [comment]
Hey, guys, any update on this? We have faced the same error
