### ISSUE TITLE
socketio-socket usage

### ISSUE THREAD

**Issue by smallbitt** [emailjs/emailjs-imap-client#198]
Hi, 
I am trying to use this library with ionic 3/4 (angular 7) but I get the well known "can't use raw socket connections" and " _net2.default.connect is not a function" errors.

Is anyone aware of how to use the imap library with ionic?
what socketio-socket is meant for? because when I try to use it I get the "can't find io variable" error as well.

Thank you for you help.

**Comment by felixhammerl** [comment]
this was meant for being able to run it in a browser, but i'll be phasing out support for socketio very soon. you'd have to be running the proxy on your browser and then passing the connection information via `ws`.

https://github.com/emailjs/emailjs-tcp-proxy/
