### ISSUE TITLE
getaddrinfo ENOTFOUND imap.cox.net

### ISSUE THREAD

**Issue by NerfDoriftar** [emailjs/emailjs-imap-client#219]
Trying connect to imap.cox.net with 993 port, but i got this error

`Could not connect to server Error: Could not open socket: getaddrinfo ENOTFOUND imap.cox.net`

Here is how i assign the instance
`imap.client = new imapConnector('imap.cox.net', 993, {
			auth: {
				user: 'lkhen***@cox.net',
				pass: '*********',
			},
			useSecureTransport: true,
			requireTLS: true,
		});`

Also without `useSecureTransport` and `requireTLS` same problem.

**Comment by NerfDoriftar** [comment]
UPD:
 same with imap.windstream.net / 993
 but imap.mail.com / 993 works, any ideas?

**Comment by MarcoCanalcar** [comment]
That looks like a problem with your DNS resolution rather than a problem with the library

What happens if you try to open the connection with telnet?
`telnet imap.cox.net 993`

**Comment by NerfDoriftar** [comment]
![Capture123](https://user-images.githubusercontent.com/12801054/68623133-73c79f80-04dc-11ea-86c2-3e82b94b8b8f.PNG)
yes, you are right!!

also i tried to login with mozilla thunder bird, same thing!

but, in my virtual machine located in this PC where i have the problem, all works fine, maybe i need to change something for fix that, can you help me?

thanks!

> 
> 
> That looks like a problem with your DNS resolution rather than a problem with the library
> 
> What happens if you try to open the connection with telnet?
> `telnet imap.cox.net 993`
