### ISSUE TITLE
Should node-forge be required from emailjs-imap-client.js

### ISSUE THREAD

**Issue by mil** [emailjs/emailjs-imap-client#76]
Title says it -- isn't emailjs-imap-client un-usable without forge so shouldn't we `import` forge as a dep?

Or is there a specific reason this isn't setup @felixhammerl

**Comment by felixhammerl** [comment]
Forge is a dependency of the socket, see: https://github.com/emailjs/emailjs-tcp-socket/blob/master/package.json

It's a JS implementation of TLS and not required where a TLS API is available natively (node, chrome apps, ff packaged apps, win universal apps)

**Comment by felixhammerl** [comment]
can this be closed or was there an underlying issue?
