### ISSUE TITLE
Looking for pop3 client.

### ISSUE THREAD

**Issue by lygstate** [emailjs/emailjs-imap-client#82]

**Comment by asutherland** [comment]
I think a better venue for a question like this is probably the email.js mailing list at https://groups.google.com/forum/#!forum/emailjs documented at http://emailjs.org/ so I'm going to close this.

But having said that, the Firefox OS mail project developed a POP3 implementation.  We never spun it off as its own library for various reasons, but you can check out what's shipping on Firefox OS v2.5 devices at https://github.com/mozilla-b2g/gaia-email-libs-and-more/tree/master/js/pop3 and a streaming refactor at https://github.com/mcav/gaia-email-libs-and-more/tree/streaming/js/pop3.  The current development branch is at https://github.com/mozilla-b2g/gaia-email-libs-and-more/tree/convoy/js/pop3 but POP3 is slightly broken.
