### ISSUE TITLE
Gmail Idle doesn't work

### ISSUE THREAD

**Issue by AndryBray** [emailjs/emailjs-imap-client#86]
Hello, I've just updated browserbox to this new module changin every callback into promise and so on..
Everything works fine (mailbox selection, email reading, ecc) **except the idle cycle for gmail** (xauth token authentication), indeed I do not receive any update event (flags, new email, ecc).

Debugging I see 
```
["Client started idling"]
["Entering idle with IDLE"]
["C:", "W8 IDLE"]
["S:", "W8 BAD Could not parse command"]
and after some time...
["Idle terminated"]
 ["S:", "* BAD [CLIENTBUG] Invalid tag"]
```

PS: the same script is working with hotmail (user/pass auth)

Am I missing anything?

**Comment by asutherland** [comment]
If you're not specifying an "id" in the options dict when you new the ImapClient, it might be worth trying that.  It wouldn't surprise me if Gmail has taken to turning off IDLE for clients it perceives as ill-behaved, and your client may be caught in the net.  Certainly it could help rule a certain class of problems out!

**Comment by AndryBray** [comment]
Hi @asutherland 
I'm trying even with the id option (name+version) but the same problem... is there anything else I could try? Thank you

**Comment by asutherland** [comment]
Oh, this is probably issue #78.

**Comment by asutherland** [comment]
Also, in the event you're using STARTTLS, probably also make sure your tcpsocket wrapper is up to date; see #81.

**Comment by asutherland** [comment]
Yeah, this is almost certainly #78.  If I manually connect using `openssl s_client -crlf -connect imap.gmail.com:993` and enter IDLE and then just send an enter it does the same thing you're seeing:
```
A3 IDLE
+ idling

A3 BAD Could not parse command

* BAD [CLIENTBUG] Invalid tag
DONE
* BAD [CLIENTBUG] Invalid tag
```

So I'm gonna close this and you should follow #78 instead.
