### ISSUE TITLE
How does your imap-client compare to node-imap?

### ISSUE THREAD

**Issue by guettli** [emailjs/emailjs-imap-client#88]
How does your imap-client compare to node-imap?

https://github.com/mscdex/node-imap

**Comment by asutherland** [comment]
Speaking as a sometimes-contributor: For the FxOS gaia mail backend we used to use node-imap but switched to emailjs-imap-client (called browserbox at the time).  That was a while ago, so I can't comment decisively, but I can describe why we switched.

One of the big differences that still seems to exist is that emailjs-imap-client is based on a parser built on the IMAP grammar (see https://github.com/emailjs/emailjs-imap-handler/blob/master/src/emailjs-imap-parser.js) whereas node-imap's is a bit more ad-hoc using a lot of regexps (see https://github.com/mscdex/node-imap/blob/master/lib/Parser.js).  A real-world problem we experienced where this was relevant was with somewhat edge-case-y BODYSTRUCTURE results that node-imap had real problems with.  We managed to hack things into shape, but there were likely still a number of possible bodystructure responses that could have broken us.

This, plus the fact that we were already using a number of other libraries from the emailjs ecosystem and emailjs was under active development encouraged us to make the move.  node-imap was pretty solid when we started using it and we had fallen behind trunk when we switched; it no doubt got more solid and continues to evolve.  You're probably fine with either library, but if you want a more rigorous parser implementation or plan to use some of the other libraries in the emailjs ecosystem, I think emailjs-imap-client is definitely the way to go.
