### ISSUE TITLE
IDLE on multiple folders

### ISSUE THREAD

**Issue by AndryBray** [emailjs/emailjs-imap-client#90]
I'm sorry if I open an issue, actually this is a question:

Please, could you suggest us what is the best practice to listen for changes on multiple mailboxes?
At the moment I created 2 imap clients, one always over INBOX and the other one is the "pointer" which has been selected by the user.
In this way I can idle always over the INBOX for new messages.

If I want to get notified when I receive new spam or when a new message has been sent (from other client) is this the right way? Do I have to open 2 new clients listening on every folder?

I even tried to open and close a new imap connection on Sent, Junk and Trash every 15, 30, 45 minutes... but after some connection gmail seems to block new connections

**Comment by andris9** [comment]
Gmail limits IMAP connections to 10 for an user. So if the user has a desktop email client open that takes up 5 connections then your app is limited to the 5 remaining connections. Fortunately Gmail has the All Mail folder that includes all messages except the ones in Trash and Junk. You can ODLE on this folder and use the Gmail labels extension to get the actual folder name the message currelty resides

**Comment by AndryBray** [comment]
Thank you @andris9 
It could be a good solution but unfortunately the client works with every kind of server/provider (not only gmail). 
Supposing my app need to listen only for Inbox, Sent, Junk and Trash at the same time, the better choice seems to use 4 client connected at the same time, right? Any trouble with other well known providers like Yahoo or Hotmail?

**Comment by andris9** [comment]
All providers have different limitations. You can try to listen to all folders and if it is not possible then listen only INBOX and then regularly poll other folders using the STATUS command. If something has changed then switchh over to this updated folder and see what is new.

**Comment by AndryBray** [comment]
Is there any method on this library to check for STATUS? 
I have already created a regular check every x minutes creating a new client every time.. but I see after some time the server will block requests with AUTH FAILURE message..
If I have to check for status on every single mailbox I think I have to create every time a new client for every mailbox, so it will be not so different from the current check method, am I wrong?

Thank you for your help.

**Comment by AndryBray** [comment]
I have a doubt... at the moment in my batch sync job I do this:

- create new client
- select sent folder
- check new msg
- close connection (client.close())

Is the client.close() right or do I need to call the client.logout() ?
I think I'm reaching the limit of connections because I don not run the LOGOUT cmd...

**Comment by AndryBray** [comment]
I can confirm. Maybe this is a bug. 
If I use the "close" method, after many times it happens that connection will be still alive, in fact the temporary client is printing IDLE debug inside the console (even after I closed its connection).

As far as I'm testing the .logout() method is working better than .close().
In the comment I read "Use is discouraged!" for logout method, so what do I have to use? Do you think the close method is bugged? 

Thank you

**Comment by AndryBray** [comment]
I'm sorry for trouble, even with logout after some time I have the same problem ,so maybe it's just an authentication problem on my side (xoauth2). I'll investigate and I'll let you know more.

**Comment by AndryBray** [comment]
Confirmed... the main problem about connection was because the auth token was expired. So please, I'd like to know your opinion just about the sync strategy, thank you
