### ISSUE TITLE
Can't require ImapClient

### ISSUE THREAD

**Issue by Yatekii** [emailjs/emailjs-imap-client#95]
Hey guys! I am not sure if I am that idiot or if there is a bug.
What I did:

`npm install emailjs-imap-client`

and then in my main.js:

`var ImapClient = require('emailjs-imap-client')`

Sadly I get the error: Uncaught Error: Cannot find module "emailjs-imap-client-imap"

Every other NPM module works :(

Is there an obvious mistake?
Thanks in advance!

**Comment by felixhammerl** [comment]
have you configured your paths properly? you need to configure them for the
submodules, too.

**Comment by Yatekii** [comment]
Sorry, what do you mean by that? I just did what was explained on the README :)

**Comment by felixhammerl** [comment]
sorry, i misread. i assumed you were in a browser, using requirejs. i'll look into it.

**Comment by felixhammerl** [comment]
can you post what node version you're running?

**Comment by Yatekii** [comment]
Hey!
I am using nmp v1.3.6 and node v0.10.42. I am also using webpack v1.13.0 to compile everything into a bundle which then is included in the html which then I call with my browser :P
Is that enough information?

**Comment by nifgraup** [comment]
@Yatekii I use https://www.npmjs.com/package/imports-loader#disable-amd to get emailjs modules to work with webpack.

**Comment by Yatekii** [comment]
To be honest I aint got no clue what to do from that guide :S https://gist.github.com/d9036cdfb3ae6892b1a20be077a572df
... that's my webpack.config.js

**Comment by Axel186** [comment]
+1
Trying to require module with webpack (target: "electron").

```
ERROR in ./~/emailjs-imap-client/src/emailjs-imap-client.js
Module not found: Error: Cannot resolve module 'emailjs-imap-client-imap' in <MYPATH>/node_modules/emailjs-imap-client/src
 @ ./~/emailjs-imap-client/src/emailjs-imap-client.js 5:8-140

ERROR in ./~/emailjs-imap-client/~/emailjs-imap-handler/src/emailjs-imap-compiler.js
Module not found: Error: Cannot resolve module 'emailjs-imap-formal-syntax' in <MYPATH>/node_modules/emailjs-imap-client/node_modules/emailjs-imap-handler/src
 @ ./~/emailjs-imap-client/~/emailjs-imap-handler/src/emailjs-imap-compiler.js 25:8-55

ERROR in ./~/emailjs-imap-client/~/emailjs-imap-handler/src/emailjs-imap-parser.js
Module not found: Error: Cannot resolve module 'emailjs-imap-formal-syntax' in  <MYPATH>/node_modules/emailjs-imap-client/node_modules/emailjs-imap-handler/src
```

**Comment by nifgraup** [comment]
@Yatekii I commented on the gist, I think you didn't use imports loader correctly.

**Comment by Yatekii** [comment]
@nifgraup https://gist.github.com/955cd10469d953848527ff19099b07b8 is how it looks now and I stil run into the following issues: https://gist.github.com/Yatekii/1482ead5b907a188e50dd40f3b98222d And the package is exactly where it says it can't find it (installed through npm)

**Comment by felixhammerl** [comment]
please keep in mind that node v0.10 doesn't really support ES6, so that might be an issue here.

**Comment by Yatekii** [comment]
I have no clue what you are talking about :S 
$ node --version
v4.4.5

**Comment by felixhammerl** [comment]
If somebody figured out the webpack issue, please supply a PR...

**Comment by crowecawcaw** [comment]
#104 

This fixes the issue for me. The same problem is present in several other required emailjs libraries and needs to be fixed before webpack will compile for me.

**Comment by nifgraup** [comment]
I believe #105 is a better solution

**Comment by Axel186** [comment]
Hi, I created some example to show how emailjs modules works with webpack:
https://github.com/Axel186/emailjs-and-webpack-example

Take a look - hope it will be useful!

**Comment by malahx** [comment]
I have the same issue with [create-react-app](https://github.com/facebookincubator/create-react-app) which uses webpack, any news on this bug?

@Axel186 thanks for the workarround ;) but it need to break [create-react-app](https://github.com/facebookincubator/create-react-app) to work :'(

**Comment by hiepnm** [comment]
@malahx I had the same problem with create-react-app

**Comment by hiepnm** [comment]
@nifgraup I used create-react-app to run, build my app. How to disable AMD in it?

**Comment by malahx** [comment]
Personnaly I've eject create-react-app with `react-scripts eject` (which totally uninstall react-scripts and convert all config/script) and you need to edit the config file: `config/webpack.config.dev.js` as explained by @Axel186 

Perhaps it can be done without breaking create-react-app, but you need to configure the webpack config which are in `node_modules/react-scripts/config/webpack.config.dev.js`.

**Comment by hiepnm** [comment]
@malahx thank you, but how to config webpack.config.dev.js? I'm new in webpack.

**Comment by firomero** [comment]
How can I use it from phonegap?
