### ISSUE TITLE
How to use refresh_token along with access_token when xoauth2 authentication

### ISSUE THREAD

**Issue by tojibon** [emailjs/emailjs-imap-client#96]
It seems when I use my access_token its working properly but how I can use my already saved in DB refresh_token?

```javascript
req.gmail_client = new ImapClient("imap.gmail.com", 993, {
                useSecureTransport: true,
                auth:{
                    user: loggedInUser.gmail_address,
                    xoauth2:loggedInUser.access_token
                },
                enableCompression: true
            });
```

I need it because when I use newly created access_token it seems working fine but later when I try again its showing me console error like:

```javascript
[DEBUG][2016-05-03T03:51:53.292Z][undefined] S: W2 OK Success d64mb243647028itb
[DEBUG][2016-05-03T03:51:53.295Z][undefined] Server id updated! [object Object]
[DEBUG][2016-05-03T03:51:53.301Z][undefined] Logging in...
[DEBUG][2016-05-03T03:51:53.302Z][undefined] C: W3 AUTHENTICATE XOAUTH2 "(* value hidden *)"
[DEBUG][2016-05-03T03:51:54.098Z][undefined] S: W3 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
[ERROR][2016-05-03T03:51:54.104Z][undefined] Could not connect to server Error: Invalid credentials (Failure)
[DEBUG][2016-05-03T03:51:54.110Z][undefined] Entering state: 5
[DEBUG][2016-05-03T03:51:54.111Z][undefined] Closing connection...
```

Thanks in advance

**Comment by felixhammerl** [comment]
for short lived oauth tokens, this seems to not work. so far, we haven't implemented a proper oauth workflow, which we should probably do. or you work around it yourself... solutions?

**Comment by tojibon** [comment]
No I did not work around it yet, was expecting for an available solution :( 
I am actually working on a node base project where registered user can have a gmail client inside dashboard. Thinking what is good to go with :-?

**Comment by felixhammerl** [comment]
gmail app-specific password works nicely.

**Comment by asutherland** [comment]
The Firefox OS mail app (browser-based, not node-based) used: https://github.com/mozilla-b2g/gaia-email-libs-and-more/blob/master/js/oauth.js#L104

That in conjunction with the docs at https://developers.google.com/identity/protocols/OAuth2#basicsteps may be helpful.

**Comment by felixhammerl** [comment]
is this still current? if so, please re-open
