### ISSUE TITLE
Problems retrieving maillboxes object when listing mailboxes

### ISSUE THREAD

**Issue by katacarbix** [emailjs/emailjs-imap-client#98]
Hi, I'm trying to use the `listMailboxes()` method of the imap client. Here is what I'm trying to do:

``` js
client = new ImapClient(host, port, options);
client.connect().then(() => {
	client.listMailboxes().then((mailboxes) => {
		console.dir(mailboxes);
	});
	client.close();
});
```

It runs fine, outputs the server responses in the terminal saying I've connected and it's listing mailboxes, and closes up without errors. The problem I'm having is that I can't seem to actually use the `mailboxes` object once it has gotten a response from the server.

It may be because of this notation in the readme:

``` js
client.listMailboxes().then((mailboxes) => { ... });
```

I am really unfamiliar with what's going on here. I understand `then()` is supposed to run a function once it's done, but I have never seen the `() => { ... }` notation before. It looks like it may just be shorthand for `function(){ }` but I'm just not used to that. Maybe that isn't what's causing the problems for me.

**Comment by katacarbix** [comment]
Can someone please help me out here?

**Comment by marcus433** [comment]
I believe the problem you are having is the client is closing before the response is returned. 
As BrowserBox is asynchronous the close function is actually called before the listing is completed. The following code should work.

`client = new ImapClient(host, port, options);
client.connect()
.then(client.listMailboxes)
.then((mailboxes) => {
        console.dir(mailboxes);
 })
.then(client.close);`

**Comment by asutherland** [comment]
nit: Note that unless ImapClient is now automatically binding its methods, you'd need to do something like client.listMailboxes.bind(client) and client.close.bind(client) or wrap them in arrow-functions too like `() => client.listMailboxes()` and `() => client.close`.  (Note that it's important to not wrap the arrow function body in braces if you want the implicit return of the Promise returned by listMailboxes.

**Comment by marcus433** [comment]
Good catch @asutherland :-)

**Comment by katacarbix** [comment]
`listMailboxes` and `close` both need parentheses to run the functions, but with the two of your suggestions it works! Thank you so much!
